---
title: "Request Numbers & Population by Zip Code"
author: "Xiaoqiu Yu"
date: "11/26/2016"
output: pdf_document
---

```{r, message=FALSE}
library(ggplot2)
library(ggmap)

library(devtools)
install_github('arilamstein/choroplethrZip@v1.5.0')
library(choroplethrZip)
library(dplyr)

```

```{r}
### GET REQUEST COUNT BY ZIP CODE

# summarize the request count by zip code
reqnum=
data1 %>%
  group_by(ZipCode) %>%
  summarise(Request_Number= n())
```

```{r}
### GET POPULATION DATA FOR CHOROPLETH
pop=read.csv("popbyzip.csv")
zippop=pop[, 1:2]
colnames(zippop)=c("region","value")
popchoro=merge(zippop, reqnum, by.x="region", by.y="ZipCode")
popchoro$region=as.character(popchoro$region)

```

```{r}
range= popchoro[, 1]
zip_choro= zip_choropleth(popchoro, 
                          zip_zoom = range,
                          title= "Request Numbers and Population by Zip Code",
                          legend = "Population by Zip Code",
                          reference_map = TRUE)

library(zipcode)
data(zipcode)
reqpoly=merge(zipcode, reqnum, by.x="zip", by.y="ZipCode")


zip_choro + 
  geom_point(dat=reqpoly,
             aes(x=longitude, y=latitude, size= Request_Number),
             alpha=0.3, col= "brown")

```




